name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
      - uses: actions/checkout@v4

      - name: Install ClamAV
        run: |
          sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
          sudo service clamav-freshclam stop
          sudo freshclam --verbose
          sudo service clamav-daemon start

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox and tox-gh-actions
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox
